services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/threatlog-ai-api:1.0.0
    container_name: threatlog-ai-api
    restart: unless-stopped
    command: fastapi run app/main.py --host 0.0.0.0 --port 8000 # Production mode
    env_file: .env.api
    depends_on:
      - db
  db:
    image: mariadb:11.6.2
    container_name: threatlog-ai-db
    restart: unless-stopped
    env_file: .env.api
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
