services:
  api:
    image: ghcr.io/deathlockers/tlapi:master
    container_name: threatlog-ai-api
    restart: unless-stopped
    command: fastapi run app/main.py --host 0.0.0.0 --port 8000 # Production mode
    env_file: .env.api
    depends_on:
      - db
    ports:
    - "8000:8000"
  db:
    image: mariadb:11.6.2
    container_name: threatlog-ai-db
    restart: unless-stopped
    env_file: .env.api
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
